### ISSUE TITLE
When building my app on a new machine, I get the following error after copying my token and returning to the app

### ISSUE THREAD

**Issue by GroovinChip** [lukepighetti/mastodon-dart#10]
```
E/flutter (21006): [ERROR:flutter/shell/common/shell.cc(186)] Dart Error: Unhandled exception:
E/flutter (21006): Unsupported operation: Cannot modify an unmodifiable Map
E/flutter (21006): #0      _ImmutableMap.removeWhere (dart:core/runtime/libimmutable_map.dart:118:5)
E/flutter (21006): #1      __Base&Authentication&Utilities.request (package:mastodon/src/utilities.dart:23:31)
E/flutter (21006): <asynchronous suspension>
E/flutter (21006): #2      _Mastodon&_Base&Accounts.verifyCredentials (package:mastodon/src/endpoints/accounts.dart:57:28)
E/flutter (21006): <asynchronous suspension>
E/flutter (21006): #3      AuthBloc._handleToken (package:mastodon/src/bloc/auth.dart:131:38)
E/flutter (21006): <asynchronous suspension>
E/flutter (21006): #4      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
E/flutter (21006): #5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
E/flutter (21006): #6      _DelayedData.perform (dart:async/stream_impl.dart:591:14)
E/flutter (21006): #7      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
E/flutter (21006): #8      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
E/flutter (21006): #9      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (21006): #10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)```

**Comment by lukepighetti** [comment]
https://github.com/lukepighetti/mastodon-dart/commit/63d0d0ac2aade01b07ddca9b09ab1aea809b1ffb should fix it, please close if so

**Comment by GroovinChip** [comment]
Having issues forcing AS to get the newest version, will report back when I can get it to work

**Comment by GroovinChip** [comment]
I got the newest version, still getting the same error.
